on:
  pull_request:
    branches:
      - 'develop'

jobs:
  android-build-check-and-shared-tests:
    name: Build android app and run shared tests.
    runs-on: ubuntu-latest

    env:
      API_KEY_TMDB: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build androidApp
        run: gradle :androidApp:buildDebug

      - name: Run unit tests
        run: gradle :shared:testDebugUnitTest

  ios-build-check:
    name: Build iosApp
    runs-on: macos-15

    env:
      API_KEY_TMDB: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version # Optional: verify selected version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build iosApp
        run: |
          xcodebuild clean build -project iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.3.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    #- name: Run Ios tests
    #  run: bash xcodebuild test -workspace iosApp/iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
